/*$file${components::test::.::test.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: get-started.qm
* File:  ${components::test::.::test.h}
*
* This code has been generated by QM 4.5.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${components::test::.::test.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef TEST_H
#define TEST_H

#define TEST_TICK_INTERVAL_MS        (1000)

/* opaque pointers to active objects */
/*$declare${components::test::AO_test} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
extern QActive * const AO_test;
/*$enddecl${components::test::AO_test} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$declare${components::test::TEST_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${components::test::TEST_ctor} ...........................................*/
void TEST_ctor(void);
/*$enddecl${components::test::TEST_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* TEST_H */