/*$file${.::priorityList.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: get-started.qm
* File:  ${.::priorityList.h}
*
* This code has been generated by QM 4.5.1 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #   : QPC-ANY-171208A
* Issued to   : Zimplistic Private Limited
* Framework(s): qpc
* Support ends: 2019-12-08
* Product(s)  :
* Any product of Zimplistic Private Limited
*/
/*$endhead${.::priorityList.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef PRIORITY_LIST_H
#define PRIORITY_LIST_H

enum task_priority {
    PRIORITY_QSPY = tskIDLE_PRIORITY + 1,
    PRIORITY_TEST,

    PRIORITY_MAX
};

/* freeRTOS task priority should be less than configMAX_PRIORITIES
 * as defined in FreeRTOSConfig.h
 */
Q_ASSERT_COMPILE(PRIORITY_MAX < configMAX_PRIORITIES);

#endif /* PRIORITY_LIST_H */