/*$file${.::signalList.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: get-started.qm
* File:  ${.::signalList.h}
*
* This code has been generated by QM 4.5.1 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #   : QPC-ANY-171208A
* Issued to   : Zimplistic Private Limited
* Framework(s): qpc
* Support ends: 2019-12-08
* Product(s)  :
* Any product of Zimplistic Private Limited
*/
/*$endhead${.::signalList.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef SIGNAL_LIST_H
#define SIGNAL_LIST_H

enum testSignal {
    // Events/Signals that are published **************************************
    /* Published Sensor Signals */
    TEST_READY_SIG = Q_USER_SIG,
    TEST_SIG,

    MAX_PUB_SIG,                            // last published signal

    // Events/Signals that are posted directly *******************************
    GET_OBJECT_DICTIONARY_SIG,
    GET_FUNC_DICTIONARY_SIG,
    GET_SIGNAL_DICTIONARY_SIG,
    /* Module Generic Signal */
    TICK_SIG,

    MAX_SIG
};

#endif /* SIGNAL_LIST_H */