#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := $(notdir $(shell pwd))
CFLAGS += -DQ_SPY

include $(ESP_QPC_PATH)/project.mk
