/*$file${components::test::.::test.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: get-started.qm
* File:  ${components::test::.::test.h}
*
* This code has been generated by QM 4.5.1 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #   : QPC-ANY-171208A
* Issued to   : Zimplistic Private Limited
* Framework(s): qpc
* Support ends: 2019-12-08
* Product(s)  :
* Any product of Zimplistic Private Limited
*/
/*$endhead${components::test::.::test.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef TEST_H
#define TEST_H

#define TEST_TICK_INTERVAL_MS        (1000)

/* opaque pointers to active objects */
/*$declare${components::test::AO_test} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
extern QActive * const AO_test;
/*$enddecl${components::test::AO_test} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$declare${components::test::TEST_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${components::test::TEST_ctor} ...........................................*/
void TEST_ctor(void);
/*$enddecl${components::test::TEST_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* TEST_H */